# ----------------------------
# Makefile Options
# ----------------------------

NAME = VID84
ICON = icon.png
DESCRIPTION = "84VID Decoder"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
